### PR TITLE
Configure plugin more lazily

### LINKED ISSUE #119: Add support of Android Application gradle module
Hi, looks like a very useful project, I have been trying to get your project to work in my Kotlin multiplatform (Android & iOS) project. It is a single Gradle project for both apps, using Android Application plugin, not Android Library plugin.

No errors appear, but the `generateMRcommonMain` task is missing, and of course no resources are generated. The line below leads me to believe only library projects are supported. All your sample projects are library projects.

https://github.com/icerockdev/moko-resources/blob/e2750b5b03c811d1b4611b9d08c92f958cdd7a2e/plugins/resources-generator/src/main/kotlin/dev/icerock/gradle/MultiplatformResourcesPlugin.kt#L46

Why - can you not also support Android Application projects? Or please have some warning documentation to make this clear for people in the future?

### LINKED ISSUE #510: Build failed with Kotlin 1.9.0-Beta
https://github.com/xpathexception/MokoResourcesIssue/tree/0c74975b7cf0a6581fb1113711dd73e4a0596ec6

here problem reproduced.

android build - `./gradlew :frontend:app:buildDebug`
```
> Task :frontend:modules:features:sample:compileDebugKotlinAndroid FAILED
e: file:///Users/amikhailov/Documents/projects/sandbox/MokoResourcesIssue/frontend/modules/features/sample/build/generated/moko/commonMain/src/com/example/myapp/features/sample/sampleR.kt:12:22 Expected object 'sampleR' has no actual declaration in module <sample_debug> for JVM

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:modules:features:sample:compileDebugKotlinAndroid'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
as i see `frontend/modules/features/sample/build/generated/moko/androidMain/src` not marked as source root.

web build - `./gradlew :frontend:app-web:jsBrowserDevelopmentRun`
```
> Task :frontend:modules:features:sample:compileKotlinJs FAILED
e: file:///Users/amikhailov/Documents/projects/sandbox/MokoResourcesIssue/frontend/modules/features/sample/build/generated/moko/commonMain/src/com/example/myapp/features/sample/sampleR.kt:12:22 Expected object 'sampleR' has no actual declaration in module <MokoResourcesIssue.frontend.modules.features:sample> for JS

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:modules:features:sample:compileKotlinJs'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
same problem - `frontend/modules/features/sample/build/generated/moko/jsMain/src` not marked as source root

### PR DESCRIPTION
**Pull request by illarionov**
This is the second approach to fix #510, #531.
Configure the plugin more lazily, leverage Gradle Lazy Configuration API and Gradle live collections.

Android configuration is completely moved to `AndroidPluginLogic` to fix #119.

### CODE REVIEW

**Comment by creativedrewy** [comment]
Please merge! I'd love to get this working in a project I've got using 1.9.0

**Comment by Pschsch** [comment]
After all, I've tested this PR by connecting it as composite build with Kotlin 1.9.0 and KSP 1.9.0 by issue #535. Problem still exists((

**Comment by illarionov** [comment]
@Pschsch actually, in this case, it's hard for me to understand what the issue is in #535.
In the second comment there is an error message:
```
 Task ':compileKotlinJvm' uses this output of task ':generateMRcommonMain' without declaring an explicit or implicit dependency.
```
I think this type of error should be fixed by this PR.

I myself have stumbled upon another error that looks very similar:
```
Task ':mpp-library:iosX64ProcessResources' uses this output of task ':mpp-library:generateMRcommonMain' without declaring an explicit or implicit dependency.
```
It is reproducible if you build a project with ios targets on a non-macos host. I didn't cover this case it in this PR and I think it should be handled separately.

The very first message mentions the error message:
```
Cannot change attributes of dependency configuration ':myProject:iosX64CInteropApiElements' after it has been resolved`
```
When other plugins with KSP are used in a project (for example, with KMP-NativeCoroutines). Personally, I have never seen this error and haven't tested such a configuration. But I see some fixes, that may affect this, in KSP itself and I think this case should be addressed separately as well.

**Comment by Pschsch** [comment]
@illarionov I have pushed PR with #535 fix, tried it to build ios app on Kotlin 1.9.10 and KSP, all works fine

**Comment by Alex009** [comment]
@illarionov i close this PR because all fixes now contains in #575
