### ISSUE TITLE
Build failed with Kotlin 1.9.0-Beta

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-resources#510]
https://github.com/xpathexception/MokoResourcesIssue/tree/0c74975b7cf0a6581fb1113711dd73e4a0596ec6

here problem reproduced.

android build - `./gradlew :frontend:app:buildDebug`
```
> Task :frontend:modules:features:sample:compileDebugKotlinAndroid FAILED
e: file:///Users/amikhailov/Documents/projects/sandbox/MokoResourcesIssue/frontend/modules/features/sample/build/generated/moko/commonMain/src/com/example/myapp/features/sample/sampleR.kt:12:22 Expected object 'sampleR' has no actual declaration in module <sample_debug> for JVM

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:modules:features:sample:compileDebugKotlinAndroid'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
as i see `frontend/modules/features/sample/build/generated/moko/androidMain/src` not marked as source root.

web build - `./gradlew :frontend:app-web:jsBrowserDevelopmentRun`
```
> Task :frontend:modules:features:sample:compileKotlinJs FAILED
e: file:///Users/amikhailov/Documents/projects/sandbox/MokoResourcesIssue/frontend/modules/features/sample/build/generated/moko/commonMain/src/com/example/myapp/features/sample/sampleR.kt:12:22 Expected object 'sampleR' has no actual declaration in module <MokoResourcesIssue.frontend.modules.features:sample> for JS

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frontend:modules:features:sample:compileKotlinJs'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```
same problem - `frontend/modules/features/sample/build/generated/moko/jsMain/src` not marked as source root

**Comment by Nailik** [comment]
i just got the same problem, is there any workaround possible?

**Comment by bcmedeiros** [comment]
Same issue here, with kotlin 1.9.0 final

**Comment by ExNDY** [comment]
> i just got the same problem, is there any workaround possible?
> 
> Edit: A temporary workaround (for android) is to add this to the build.gradle.kts
> 

@Nailik , Worked solution on current time, thank you

**Comment by luca992** [comment]
After updating to 1.9.0 the `generateMRjvmMain` task isn't even available for me any more while other native targets, and android are working

**Comment by archiegq21** [comment]
> i just got the same problem, is there any workaround possible?
> 
> Edit: A temporary workaround (for android) is to add this to the build.gradle.kts
> 
> ```
> android {
>     sourceSets {
>         getByName("main").java.srcDirs("build/generated/moko/androidMain/src")
>     }
> }
> ```
> 
> For ios:
> 
> ```
> val iosX64Main by getting {
>     resources.srcDirs("build/generated/moko/iosX64Main/src")
> }
> val iosArm64Main by getting {
>    resources.srcDirs("build/generated/moko/iosArm64Main/src")
> }
> val iosSimulatorArm64Main by getting {
>    resources.srcDirs("build/generated/moko/iosSimulatorArm64Main/src")
> }
> ```

Did you find any workaround for JS?

**Comment by pitampoudel** [comment]
> i just got the same problem, is there any workaround possible?
> 
> Edit: A temporary workaround (for android) is to add this to the build.gradle.kts
> 
> ```
> android {
>     sourceSets {
>         getByName("main").java.srcDirs("build/generated/moko/androidMain/src")
>     }
> }
> ```
> 
> For ios:
> 
> ```
> val iosX64Main by getting {
>     resources.srcDirs("build/generated/moko/iosX64Main/src")
> }
> val iosArm64Main by getting {
>    resources.srcDirs("build/generated/moko/iosArm64Main/src")
> }
> val iosSimulatorArm64Main by getting {
>    resources.srcDirs("build/generated/moko/iosSimulatorArm64Main/src")
> }
> ```

@Nailik thank you for the workaround. I can run my Android app after adding this but what about jvm? I am still getting the error message when trying to run the desktop app. 

One solution would be to configure it like below but it again gives some warning about the hierarchy template.
        jvmMain.configure {
            dependsOn(commonMain.get())
        }

**Comment by Alex009** [comment]
should be fixed in 0.24.0-beta-1
