### ISSUE TITLE
Crash when using MR.strings() in unit tests

### ISSUE THREAD

**Issue by zvona031** [icerockdev/moko-resources#714]
I modularized my app with local SPM and I am trying to create tests for each module. But after running the test where I use `MR.strings()......` I get the following crash
At the end of the error it says: **Caused by: kotlin.IllegalArgumentException: bundle with identifier org.undabot.inventory.shared.main not found.**
Is there any additional setup needed for the tests?

![image (1)](https://github.com/icerockdev/moko-resources/assets/46491860/5c47fc33-5b60-494b-8e8d-1a026558c56f)
![image](https://github.com/icerockdev/moko-resources/assets/46491860/ca7553b9-8ed5-4ce5-b21b-64e03c80125a)

**Comment by Alex009** [comment]
hi. your tests in swift? not in kotlin?

if yes - i think you should add build phase with copy resources to Tests Xcode target too

**Comment by zvona031** [comment]
Yes, my tests are in Swift. The thing is that I do not have Test target where I could add build phase. I have tests directly in the local SPM package (image below)
Is the solution in that situation the same or it changes something? Can I find the sample of my situation somewhere, and how exactly the build phase looks?

**Comment by Alex009** [comment]
@zvona031 looks like you should create special Plugin for run gradle task - https://github.com/apple/swift-package-manager/blob/main/Documentation/Plugins.md

or you can change you module type from staticLibrary to dynamic

**Comment by zvona031** [comment]
Since I have never used Swift package build plugins, it is a bit confusing to me. Have you ever done something similar yourself?

**Comment by Alex009** [comment]
@zvona031 no

**Comment by zvona031** [comment]
Out of curiosity, how are the resources even working when I build my app, since I have static library and am not running any scripts for copying the resources. I am having a monorepo (shared, Android and iOS app), is that effecting this somehow?

**Comment by Alex009** [comment]
@zvona031 to works with static library in xcode should be added build phase that described in readme

**Comment by zvona031** [comment]
I saw that, but I did not add anything to my build phase, and it still works somehow. I am importing the shared code with SPM which is built using the KMMBridge.

**Comment by JuliaJakubcova** [comment]
Hi, I have the same issue. On the project we use SPM and we have a monorepo as well, but the differences are dynamic framework as opposed to static and we have the build phase. The tests look okay, MR strings are being suggested by autocomplete in Xcode, but they crash in runtime, seems the MR class is not found `IllegalArgumentException: bundle with identifier kmp.shared.MR not found`. I will be very thankful for any advice.

**Comment by zvona031** [comment]
Is it possible to get some help or advice regarding this issue?

**Comment by MAX-POLKOVNIK** [comment]
@zvona031 you can try my solution for SwiftUI previews - https://github.com/icerockdev/moko-resources/issues/747#issuecomment-2330854244

**Comment by hasancanakgunduz** [comment]
I’m encountering the same crash on iOS when strings are accessed in the unit tests of my Swift Package Manager (SPM) package. To work around it, I created a protocol and two separate string classes—one for the production code and another for the unit tests. The unit-test string class doesn’t use Moko, whereas the production one does.

**Comment by Carrione** [comment]
It seems that the solution from @MAX-POLKOVNIK unfortunately does not work in Kotlin 2.2.10 and moko-resources 0.25.0. 

```
Compilation failed: IrSimpleFunctionSymbolImpl is already bound. Signature: dev.icerock.moko.resources.utils/loadableBundle|loadableBundle@platform.Foundation.NSBundle.Companion(kotlin.String){}[0]. Owner: FUN name:loadableBundle visibility:public modality:FINAL <> (<this>:platform.Foundation.NSBundle.Companion, identifier:kotlin.String) returnType:platform.Foundation.NSBundle
```

We simply cannot override the original implementation.
